package com.example.quranapp.prefs;

import java.util.ArrayList;
import java.util.List;

public class Constant {

    public final String SharedPreferencesName = "quran_sp";
    public final String ACCOUNT_TYPE = "account_type";
    public final String SHEIKH = "sheikh";
    public final String STUDENT = "student";
    public final String PLAN = "plan";
    public final String WARD_END = "wardEnd";
    public final String NEW_WARD_START = "wardStart";
    public final String LIST_USER_ANSWERS_Q1_Q2 = "user_answers_q1_q2";
    public final String LIST_Q3_4_5_6 = "q3_4_5_6";
    public final String LIST_USER_ANSWERS_Q3_Q4_Q5_Q6 = "user_answers_q3_4_5_6";
    public final String LIST_CORRECT_ANSWERS_Q1_Q2 = "correct_answers_q1_q2";
    public final String LIST_CORRECT_ANSWERS_Q3_Q4_Q5_Q6 = "correct_answers_q3_4_5_6";

    public List<String> getSuraNameList() {
        ArrayList<String> suraNamesArrayList = new ArrayList<>();
        suraNamesArrayList.add("سورة الفاتحة");
        suraNamesArrayList.add("سورة البقرة");
        suraNamesArrayList.add("سورة آل عمران");
        suraNamesArrayList.add("سورة النساء");
        suraNamesArrayList.add("سورة المائدة");
        suraNamesArrayList.add("سورة الأنعام");
        suraNamesArrayList.add("سورة الأعراف");
        suraNamesArrayList.add("سورة الأنفال");
        suraNamesArrayList.add("سورة التوبة");
        suraNamesArrayList.add("سورة يونس");
        suraNamesArrayList.add("سورة هود");
        suraNamesArrayList.add("سورة يوسف");
        suraNamesArrayList.add("سورة الرعد");
        suraNamesArrayList.add("سورة إبراهيم");
        suraNamesArrayList.add("سورة الحجر");
        suraNamesArrayList.add("سورة النحل");
        suraNamesArrayList.add("سورة الإسراء");
        suraNamesArrayList.add("سورة الكهف");
        suraNamesArrayList.add("سورة مريم");
        suraNamesArrayList.add("سورة طه");
        suraNamesArrayList.add("سورة الأنبياء");
        suraNamesArrayList.add("سورة الحج");
        suraNamesArrayList.add("سورة المؤمنون");
        suraNamesArrayList.add("سورة النور");
        suraNamesArrayList.add("سورة الفرقان");
        suraNamesArrayList.add("سورة الشعراء");
        suraNamesArrayList.add("سورة النمل");
        suraNamesArrayList.add("سورة القصص");
        suraNamesArrayList.add("سورة العنكبوت");
        suraNamesArrayList.add("سورة الروم");
        suraNamesArrayList.add("سورة لقمان");
        suraNamesArrayList.add("سورة السجدة");
        suraNamesArrayList.add("سورة الأحزاب");
        suraNamesArrayList.add("سورة سبأ");
        suraNamesArrayList.add("سورة فاطر");
        suraNamesArrayList.add("سورة يس");
        suraNamesArrayList.add("سورة الصافات");
        suraNamesArrayList.add("سورة ص");
        suraNamesArrayList.add("سورة الزمر");
        suraNamesArrayList.add("سورة غافر");
        suraNamesArrayList.add("سورة فصلت");
        suraNamesArrayList.add("سورة الشوري");
        suraNamesArrayList.add("سورة الزخرف");
        suraNamesArrayList.add("سورة الدخان");
        suraNamesArrayList.add("سورة الجاثية");
        suraNamesArrayList.add("سورة الأحقاف");
        suraNamesArrayList.add("سورة محمد");
        suraNamesArrayList.add("سورة الفتح");
        suraNamesArrayList.add("سورة الحجرات");
        suraNamesArrayList.add("سورة ق");
        suraNamesArrayList.add("سورة الذاريات");
        suraNamesArrayList.add("سورة الطور");
        suraNamesArrayList.add("سورة النجم");
        suraNamesArrayList.add("سورة القمر");
        suraNamesArrayList.add("سورة الرحمن");
        suraNamesArrayList.add("سورة الواقعة");
        suraNamesArrayList.add("سورة الحديد");
        suraNamesArrayList.add("سورة المجادلة");
        suraNamesArrayList.add("سورة الحشر");
        suraNamesArrayList.add("سورة الممتحنة");
        suraNamesArrayList.add("سورة الصف");
        suraNamesArrayList.add("سورة الجمعة");
        suraNamesArrayList.add("سورة المنافقون");
        suraNamesArrayList.add("سورة التغابن");
        suraNamesArrayList.add("سورة الطلاق");
        suraNamesArrayList.add("سورة التحريم");
        suraNamesArrayList.add("سورة الملك");
        suraNamesArrayList.add("سورة القلم");
        suraNamesArrayList.add("سورة الحاقة");
        suraNamesArrayList.add("سورة المعارج");
        suraNamesArrayList.add("سورة نوح");
        suraNamesArrayList.add("سورة الجن");
        suraNamesArrayList.add("سورة المزمل");
        suraNamesArrayList.add("سورة المدثر");
        suraNamesArrayList.add("سورة القيامة");
        suraNamesArrayList.add("سورة الإنسان");
        suraNamesArrayList.add("سورة المرسلات");
        suraNamesArrayList.add("سورة النبأ");
        suraNamesArrayList.add("سورة النازعات");
        suraNamesArrayList.add("سورة عبس");
        suraNamesArrayList.add("سورة التكوير");
        suraNamesArrayList.add("سورة الانفطار");
        suraNamesArrayList.add("سورة المطففين");
        suraNamesArrayList.add("سورة الانشقاق");
        suraNamesArrayList.add("سورة البروج");
        suraNamesArrayList.add("سورة الطارق");
        suraNamesArrayList.add("سورة الأعلي");
        suraNamesArrayList.add("سورة الغاشية");
        suraNamesArrayList.add("سورة الفجر");
        suraNamesArrayList.add("سورة البلد");
        suraNamesArrayList.add("سورة الشمس");
        suraNamesArrayList.add("سورة الليل");
        suraNamesArrayList.add("سورة الضحي");
        suraNamesArrayList.add("سورة الشرح");
        suraNamesArrayList.add("سورة التين");
        suraNamesArrayList.add("سورة العلق");
        suraNamesArrayList.add("سورة القدر");
        suraNamesArrayList.add("سورة البينة");
        suraNamesArrayList.add("سورة الزلزلة");
        suraNamesArrayList.add("سورة العاديات");
        suraNamesArrayList.add("سورة القارعة");
        suraNamesArrayList.add("سورة التكاثر");
        suraNamesArrayList.add("سورة العصر");
        suraNamesArrayList.add("سورة الهمزة");
        suraNamesArrayList.add("سورة الفيل");
        suraNamesArrayList.add("سورة قريش");
        suraNamesArrayList.add("سورة الماعون");
        suraNamesArrayList.add("سورة الكوثر");
        suraNamesArrayList.add("سورة الكافرون");
        suraNamesArrayList.add("سورة النصر");
        suraNamesArrayList.add("سورة المسد");
        suraNamesArrayList.add("سورة الإخلاص");
        suraNamesArrayList.add("سورة الفلق");
        suraNamesArrayList.add("سورة الناس");

        return suraNamesArrayList;
    }
}
